%**********************************************************************
%QuantStudio - MATLAB IO Utility.
%Author: Aron Mandrella
%@2018
%**********************************************************************/

if ~isdeployed
    clc;
    addpath('functions_diagrams');
    addpath('functions_utility');
end

%% INFORMACJA U¯YTKOWA:
msg = {...
    'By wygenerowaæ wykresy:',...
    '- wska¿ wygenerowane pliki *.csv w folderze ‘per_method_data,’',...
    '- wska¿ miejsce zapisu,',...
    '- wska¿ folder z oryginalnymi grafikami,',...
    '- ustaw parametry wykresów (klikaj¹c zawsze Ok wygenerujesz wykresy z domyœlnymi ustawieniami)',...
    ' ',...
    'UWAGA:',...
    'By wykresy zosta³y poprawnie stworzone dane w plikach wejœciowych musz¹ byæ wygenerowane z zaznaczon¹ opcj¹ “wyniki procentowe”.'};
f = msgbox(msg, 'QuantStudio - Generowanie wykresów');
waitfor(f);

%% POBRANIE INFORMACJI O PORZEBNYCH PLIKACH:
[...
    filenames,...
    save_path,...
    images_path,...
    tf...
] = inputDiagramFiles();
if tf == 0
    return;
end


%% POBRANIE USTAWIEÑ WYKRESÓW:
[...
    diagram_types, diagram_count_fun,...
    flag_sets, flag_sets_names,...
    additional_flags,...
    metrics_group, metrics_solo, metrics_image,...
    bar_metrics, bar_tensions, bar_weights,...
    rescale,...
    tf...
] = inputDiagramsSettings();
if tf == 0
    return;
end
diagram_count = diagram_count_fun(length(filenames));


%% GENEROWANIE WYKRESÓW:
tf = createDiagramsLogic(...
    diagram_types, diagram_count,...
    flag_sets, flag_sets_names,...
    additional_flags,...
    metrics_group, metrics_solo, metrics_image,...
    bar_metrics, bar_tensions, bar_weights,...
    rescale,...
    filenames,...
    save_path,...
    images_path...
);


%% ZAKOÑCZENIE PRACY:
if(tf==1)
    answer = questdlg({'Zakoñczono generowanie wykresów.',...
        'Otworzyæ folder z wynikami?'}, ...
        'Zakoñczono', 'Tak','Nie', 'Nie');
else
    answer = questdlg({'Anulowano generowanie wykresów.',...
        'Otworzyæ folder z dotychczasowymi wynikami?'}, ...
        'Anulowano', 'Tak','Nie', 'Nie');
end
switch answer
    case 'Tak'
        winopen(save_path);
end